CREATE TABLE Client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL CHECK (LENGTH(name) >= 3)
);

CREATE TABLE Planet (
    id VARCHAR(255) CHECK (id REGEXP '^[A-Z0-9]*$'),
    name VARCHAR(500) NOT NULL CHECK (LENGTH(name) >= 1)
);

CREATE TABLE Ticket (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    client_id INT NOT NULL, FOREIGN KEY (client_id) REFERENCES Client(id),
    from_planet_id VARCHAR(255) NOT NULL,
    to_planet_id VARCHAR(255) NOT NULL
);